target: p3.cpp
	g++ -O2 -fsanitize=undefined -fsanitize=address -std=c++17 -o p3 p3.cpp
	g++ -O2 -fsanitize=undefined -fsanitize=address -std=c++17 -o bf bf.cpp
	# ./p2 < p2_sample3.txt
make clean:
	rm -f bf
	rm -f p3